apiVersion: v1
kind: ServiceAccount
metadata:
  name: aws-load-balancer-controller
  namespace: kube-system
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::353452453400:role/eks_project-aws-lb-controller-ee3933ab33da41b2f6bc3d983a